# language_full_map.py

LANGUAGE_FULL_MAP = {
    "cdo": "Min Dong Chinese",
    "glk": "Gilaki",
    "jam": "Jamaican Creole English",
    "lug": "Ganda",
    "san": "Sanskrit",
    "rue": "Rusyn",
    "wol": "Wolof",
    "new": "Nepal Bhasa",
    "mwl": "Mirandese",
    "bre": "Breton",
    "ara": "Arabic",
    "hye": "Armenian",
    "xmf": "Mingrelian",
    "ext": "Extremaduran",
    "cor": "Cornish",
    "yor": "Yoruba",
    "div": "Dhivehi",
    "asm": "Assamese",
    "lat": "Latin",
    "cym": "Welsh",
    "hif": "Fiji Hindi",
    "ace": "Achinese",
    "kbd": "Kabardian",
    "tgk": "Tajik",
    "rus": "Russian",
    "nso": "Northern Sotho",
    "mya": "Burmese",
    "msa": "Malay",
    "ava": "Avar",
    "cbk": "Chavacano",
    "urd": "Urdu",
    "deu": "German",
    "swa": "Swahili",
    "pus": "Pashto",
    "bxr": "Buriat",
    "udm": "Udmurt",
    "csb": "Kashubian",
    "yid": "Yiddish",
    "vro": "Võro",
    "por": "Portuguese",
    "pdc": "Pennsylvania German",
    "eng": "English",
    "tha": "Thai",
    "hat": "Haitian",
    "lmo": "Lombard",
    "pag": "Pangasinan",
    "jav": "Javanese",
    "chv": "Chuvash",
    "nan": "Min Nan Chinese",
    "sco": "Scots",
    "kat": "Georgian",
    "bho": "Bhojpuri",
    "bos": "Bosnian",
    "kok": "Konkani",
    "oss": "Ossetic",
    "mri": "Māori",
    "fry": "Frisian",
    "cat": "Catalan",
    "azb": "South Azerbaijani",
    "kin": "Kinyarwanda",
    "hin": "Hindi",
    "sna": "Shona",
    "dan": "Danish",
    "egl": "Emilian",
    "mkd": "Macedonian",
    "ron": "Romanian",
    "bul": "Bulgarian",
    "hrv": "Croatian",
    "som": "Somali",
    "pam": "Pampangan",
    "nav": "Navajo",
    "ksh": "Colognian",
    "nci": "Classical Occitan",
    "khm": "Khmer",
    "sgs": "Samogitian",
    "srn": "Sranan Tongo",
    "bar": "Bavarian",
    "cos": "Corsican",
    "ckb": "Sorani Kurdish",
    "pfl": "Palatine German",
    "arz": "Egyptian Arabic",
    "roa-tara": "Tarantino",
    "fra": "French",
    "mai": "Maithili",
    "zh-yue": "Cantonese",
    "guj": "Gujarati",
    "fin": "Finnish",
    "kir": "Kirghiz",
    "vol": "Volapük",
    "hau": "Hausa",
    "afr": "Afrikaans",
    "uig": "Uighur",
    "lao": "Lao",
    "swe": "Swedish",
    "slv": "Slovenian",
    "kor": "Korean",
    "szl": "Silesian",
    "srp": "Serbian",
    "dty": "Dotyali",
    "nrm": "Norman",
    "dsb": "Lower Sorbian",
    "ind": "Indonesian",
    "wln": "Walloon",
    "pnb": "Western Punjabi",
    "ukr": "Ukrainian",
    "bpy": "Bishnupriya",
    "vie": "Vietnamese",
    "tur": "Turkish",
    "aym": "Aymara",
    "lit": "Lithuanian",
    "zea": "Zeelandic",
    "pol": "Polish",
    "est": "Estonian",
    "scn": "Sicilian",
    "vls": "West Flemish",
    "stq": "Saterland Frisian",
    "gag": "Gagauz",
    "grn": "Guarani",
    "kaz": "Kazakh",
    "ben": "Bengali",
    "pcd": "Picard",
    "bjn": "Banjar",
    "krc": "Karachay-Balkar",
    "amh": "Amharic",
    "diq": "Dimli",
    "ltz": "Luxembourgish",
    "ita": "Italian",
    "kab": "Kabyle",
    "bel": "Belarusian",
    "ang": "Old English",
    "mhr": "Mari",
    "che": "Chechen",
    "koi": "Komi-Permyak",
    "glv": "Manx",
    "ido": "Ido",
    "fao": "Faroese",
    "bak": "Bashkir",
    "isl": "Icelandic",
    "bcl": "Bikol",
    "tet": "Tetum",
    "jpn": "Japanese",
    "kur": "Kurdish",
    "map-bms": "Banyumasan",
    "tyv": "Tuvan",
    "olo": "Olonets Karelian",
    "arg": "Aragonese",
    "ori": "Odia",
    "lim": "Limburgish",
    "tel": "Telugu",
    "lin": "Lingala",
    "roh": "Romansh",
    "sqi": "Albanian",
    "xho": "Xhosa",
    "mlg": "Malagasy",
    "fas": "Persian",
    "hbs": "Serbo-Croatian",
    "tam": "Tamil",
    "aze": "Azerbaijani",
    "lad": "Ladino",
    "nob": "Norwegian Bokmål",
    "sin": "Sinhala",
    "gla": "Scottish Gaelic",
    "nap": "Neapolitan",
    "snd": "Sindhi",
    "ast": "Asturian",
    "mal": "Malayalam",
    "mdf": "Moksha",
    "tsn": "Tswana",
    "nds": "Low German",
    "tgl": "Tagalog",
    "nno": "Norwegian Nynorsk",
    "sun": "Sundanese",
    "lzh": "Classical Chinese",
    "jbo": "Lojban",
    "crh": "Crimean Tatar",
    "pap": "Papiamento",
    "oci": "Occitan",
    "hak": "Hakka Chinese",
    "uzb": "Uzbek",
    "zho": "Mandarin Chinese",
    "hsb": "Upper Sorbian",
    "sme": "Northern Sami",
    "mlt": "Maltese",
    "vep": "Veps",
    "lez": "Lezghian",
    "nld": "Dutch",
    "nds-nl": "Dutch Low Saxon",
    "mrj": "Meadow Mari",
    "spa": "Spanish",
    "ceb": "Cebuano",
    "ina": "Interlingua",
    "heb": "Hebrew",
    "hun": "Hungarian",
    "que": "Quechua",
    "kaa": "Karakalpak",
    "mar": "Marathi",
    "vec": "Venetian",
    "frp": "Arpitan",
    "ell": "Greek",
    "sah": "Sakha",
    "eus": "Basque",
    "ces": "Czech",
    "slk": "Slovak",
    "chr": "Cherokee",
    "lij": "Ligurian",
    "nep": "Nepali",
    "srd": "Sardinian",
    "ilo": "Ilocano",
    "be-tarask": "Belarusian (Taraškievica)",
    "bod": "Tibetan",
    "orm": "Oromo",
    "war": "Waray",
    "glg": "Galician",
    "mon": "Mongolian",
    "gle": "Irish",
    "min": "Minangkabau",
    "ibo": "Igbo",
    "ile": "Interlingue",
    "epo": "Esperanto",
    "lav": "Latvian",
    "lrc": "Luri",
    "als": "Albanian (Switzerland)",
    "mzn": "Mazanderani",
    "rup": "Aromanian",
    "fur": "Friulian",
    "tat": "Tatar",
    "myv": "Erzya",
    "pan": "Punjabi",
    "ton": "Tonga",
    "kom": "Komi-Zyrian",
    "wuu": "Shanghainese",
    "tcy": "Tulu",
    "tuk": "Turkmen",
    "kan": "Kannada",
    "ltg": "Latgalian"
}